<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <meta name="baidu-site-verification" content="fk7KxxZA62" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
      calmari日志提示OperationalError Permission denied
    </title>
    <!--
    <link rel="shortcut icon" type="image/x-icon" href="/static/images/favicon.ico" media="screen" />
     -->
    <!-- Bootstrap Core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootstrap/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/static/css/blog.css" rel="stylesheet">
    <link href="/static/css/pygments.css" rel="stylesheet">
    <script src="/static/js/jquery-1.11.0.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media
    queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file://
    -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js">
      </script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js">
      </script>
    <![endif]-->
    <script>
        var _hmt = _hmt || [];
        (function() {
          var hm = document.createElement("script");
          hm.src = "//hm.baidu.com/hm.js?4a7b2b2a1ee8b8686ec632c195bbd833";
          var s = document.getElementsByTagName("script")[0]; 
          s.parentNode.insertBefore(hm, s);
        })();
    </script>
  </head>
  
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top " role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand " href="/" >妙音</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/categories.html">分 类</a></li>
                <li><a href="/fofa.html">学佛</a></li>
                <li><a href="/tools.html">工具</a></li>
            </ul>
            <form class="navbar-form navbar-right" role="search" action="https://www.google.com/search" method="get">
              <div class="input-group">
                <input type="text" name="q" class="form-control search-query" placeholder="搜索">
                <input type="hidden" name="ie" value="UTF-8" />
                <input type="hidden" name="sitesearch" value="www.zhulinjingshe.cn" />
              </div>
            </form>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="content">
          <div class="row">
            <!-- Blog Post -->
<!-- Title -->
<h2>
  calmari日志提示OperationalError Permission denied
  <div class="post-date">
        妙音 posted @
        <span class="glyphicon glyphicon-time"></span>
        2015-11-04 10:50
        in calamri with tags 
  </div>
</h2>
<!-- Author -->
<hr>

<div class="col-md-10">
    <h3>问题</h3>

<p>在fedora22系统中部署calmari，使用calamari-ctl initialize启动calamari后，访问浏览器，浏览器提示500。查看日志文件/var/log/calmari/httpd_error.log，得到以下内容。</p>
<div class="highlight"><pre><code class="language-text" data-lang="text">[Tue Nov 03 19:42:01.210895 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168] mod_wsgi (pid=8586): Exception occurred processing WSGI script &#39;/opt/calamari/conf/calamari.wsgi&#39;.
[Tue Nov 03 19:42:01.210915 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168] Traceback (most recent call last):
[Tue Nov 03 19:42:01.210931 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/wsgi.py&quot;, line 255, in __call__
[Tue Nov 03 19:42:01.211007 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     response = self.get_response(request)
[Tue Nov 03 19:42:01.211018 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 178, in get_response
[Tue Nov 03 19:42:01.211032 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[Tue Nov 03 19:42:01.211040 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 220, in handle_uncaught_exception
[Tue Nov 03 19:42:01.211050 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     if resolver.urlconf_module is None:
[Tue Nov 03 19:42:01.211056 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/core/urlresolvers.py&quot;, line 342, in urlconf_module
[Tue Nov 03 19:42:01.211066 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     self._urlconf_module = import_module(self.urlconf_name)
[Tue Nov 03 19:42:01.211080 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/utils/importlib.py&quot;, line 35, in import_module
[Tue Nov 03 19:42:01.211091 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     __import__(name)
[Tue Nov 03 19:42:01.211097 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/urls.py&quot;, line 20, in &lt;module&gt;
[Tue Nov 03 19:42:01.211109 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     url(r&#39;^api/v1/&#39;, include(&#39;calamari_rest.urls.v1&#39;)),
[Tue Nov 03 19:42:01.211115 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/conf/urls/__init__.py&quot;, line 25, in include
[Tue Nov 03 19:42:01.211125 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     urlconf_module = import_module(urlconf_module)
[Tue Nov 03 19:42:01.211131 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/utils/importlib.py&quot;, line 35, in import_module
[Tue Nov 03 19:42:01.211139 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     __import__(name)
[Tue Nov 03 19:42:01.211145 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/calamari_rest_api-0.1-py2.7.egg/calamari_rest/urls/v1.py&quot;, line 3, in &lt;module&gt;
[Tue Nov 03 19:42:01.211156 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     import calamari_rest.views.v1
[Tue Nov 03 19:42:01.211162 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/calamari_rest_api-0.1-py2.7.egg/calamari_rest/views/v1.py&quot;, line 33, in &lt;module&gt;
[Tue Nov 03 19:42:01.211171 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     from graphite.render.datalib import fetchData
[Tue Nov 03 19:42:01.211177 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/graphite/render/datalib.py&quot;, line 20, in &lt;module&gt;
[Tue Nov 03 19:42:01.211187 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     from graphite.storage import STORE, LOCAL_STORE
[Tue Nov 03 19:42:01.211192 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/graphite/storage.py&quot;, line 7, in &lt;module&gt;
[Tue Nov 03 19:42:01.211201 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     from graphite.remote_storage import RemoteStore
[Tue Nov 03 19:42:01.211207 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/graphite/remote_storage.py&quot;, line 8, in &lt;module&gt;
[Tue Nov 03 19:42:01.211216 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     from graphite.util import unpickle
[Tue Nov 03 19:42:01.211221 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/graphite/util.py&quot;, line 71, in &lt;module&gt;
[Tue Nov 03 19:42:01.211230 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     defaultUser = User.objects.get(username=&#39;default&#39;)
[Tue Nov 03 19:42:01.211235 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/manager.py&quot;, line 143, in get
[Tue Nov 03 19:42:01.211245 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     return self.get_query_set().get(*args, **kwargs)
[Tue Nov 03 19:42:01.211251 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 382, in get
[Tue Nov 03 19:42:01.211259 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     num = len(clone)
[Tue Nov 03 19:42:01.211265 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 90, in __len__
[Tue Nov 03 19:42:01.211272 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     self._result_cache = list(self.iterator())
[Tue Nov 03 19:42:01.211282 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/query.py&quot;, line 301, in iterator
[Tue Nov 03 19:42:01.211290 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     for row in compiler.results_iter():
[Tue Nov 03 19:42:01.211295 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py&quot;, line 775, in results_iter
[Tue Nov 03 19:42:01.211305 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     for rows in self.execute_sql(MULTI):
[Tue Nov 03 19:42:01.211310 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py&quot;, line 839, in execute_sql
[Tue Nov 03 19:42:01.211318 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     cursor = self.connection.cursor()
[Tue Nov 03 19:42:01.211324 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/__init__.py&quot;, line 326, in cursor
[Tue Nov 03 19:42:01.211333 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     cursor = util.CursorWrapper(self._cursor(), self)
[Tue Nov 03 19:42:01.211339 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py&quot;, line 182, in _cursor
[Tue Nov 03 19:42:01.211348 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     self.connection = Database.connect(**conn_params)
[Tue Nov 03 19:42:01.211354 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]   File &quot;/opt/calamari/venv/lib/python2.7/site-packages/psycopg2/__init__.py&quot;, line 167, in connect
[Tue Nov 03 19:42:01.211363 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168]     conn = _connect(dsn, connection_factory=connection_factory, async=async)
[Tue Nov 03 19:42:01.211376 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168] OperationalError: could not connect to server: Permission denied
[Tue Nov 03 19:42:01.211380 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168] \tIs the server running on host &quot;localhost&quot; (127.0.0.1) and accepting
[Tue Nov 03 19:42:01.211383 2015] [wsgi:error] [pid 8586] [remote 127.0.0.1:168] \tTCP/IP connections on port 5432?
</code></pre></div>
<h3>方法</h3>

<p>原因可能是postgresql自身访问限制、用户权限问题，检查后均被排除。查询资料得知，访问权限被selinux限制了。</p>

<p>第一种方法是设置selinux去掉访问限制</p>
<div class="highlight"><pre><code class="language-text" data-lang="text">sudo setsebool -P httpd_can_network_connect_db on
</code></pre></div>
<p>第二种方法是关闭selinux</p>

<p>编辑/etc/selinux/config，将参数配为禁用，再重启系统。</p>
<div class="highlight"><pre><code class="language-text" data-lang="text">SELINUX=disabled
</code></pre></div>
<h3>相关命令</h3>
<div class="highlight"><pre><code class="language-text" data-lang="text">getsebool -a 查看selinux控制项
</code></pre></div>
    <br/>
    <div style="margin-top:10px;margin-bottom:10px">
      
      <span class="next">
        上篇：
        <a href="/python/2015/09/09/gettext.html">
          gettext国际化用法示例
        </a>
      </span>
       
      
      <span class="prev">
        下篇：
        <a href="/linux/2015/11/10/ssh-ask.html">
          去掉ssh初次登录询问yes/no
        </a>
      </span>
      
    </div>
    <hr>
    <!-- Blog Comments -->
    <div class="media">
        <!-- UY BEGIN -->
        <div id="uyan_frame"></div>
        <script type="text/javascript" src="http://v2.uyan.cc/code/uyan.js?uid=1965284"></script>
        <!-- UY END -->
    </div>
</div>

          </div>
      </div>
      <!-- Footer -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p align="center"></p>
          </div>
        </div>
      </footer>
    </div>
    <script src="/static/js/blog.js"></script>
  </body>
</html>

